/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/airplane/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PUSHILIN_Plane_Circle000.geometry} material={materials.plane} position={[0.01, 0.03, 0]} rotation={[0, 0, 0.05]} />
      <mesh geometry={nodes.PUSHILIN_Plane_Circle001.geometry} material={materials.plane} position={[1.06, 0.31, 0]} rotation={[1.33, 0.25, -0.15]} />
    </group>
  )
}

useGLTF.preload('/model.glb')
